# Generated by Django 3.1.2 on 2020-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_productos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='date',
            field=models.BigIntegerField(default=0),
        ),
    ]
