# Generated by Django 3.1.2 on 2020-10-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_auto_20201014_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='price',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='status',
            field=models.IntegerField(default=100),
        ),
    ]
