# Generated by Django 3.1.2 on 2020-10-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_auto_20201014_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='category',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
