# Generated by Django 3.1.2 on 2020-10-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_productos_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=150)),
                ('status', models.IntegerField(default=100)),
                ('date', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
