# Generated by Django 3.1.2 on 2020-10-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_auto_20201014_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=200),
        ),
    ]
