# Generated by Django 3.1.2 on 2020-10-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0009_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
