# Generated by Django 3.1.2 on 2020-10-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0011_auto_20201019_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='earnings',
            field=models.FloatField(default=0),
        ),
    ]
